USE [master]
GO
/****** Object:  Database [Monteflix]    Script Date: 3/30/2022 2:39:13 PM ******/
CREATE DATABASE [Monteflix]
GO
ALTER DATABASE [Monteflix] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Monteflix].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Monteflix] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Monteflix] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Monteflix] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Monteflix] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Monteflix] SET ARITHABORT OFF 
GO
ALTER DATABASE [Monteflix] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Monteflix] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Monteflix] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Monteflix] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Monteflix] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Monteflix] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Monteflix] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Monteflix] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Monteflix] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Monteflix] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Monteflix] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Monteflix] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Monteflix] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Monteflix] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Monteflix] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Monteflix] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Monteflix] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Monteflix] SET RECOVERY FULL 
GO
ALTER DATABASE [Monteflix] SET  MULTI_USER 
GO
ALTER DATABASE [Monteflix] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Monteflix] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Monteflix] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Monteflix] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Monteflix] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Monteflix] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Monteflix', N'ON'
GO
ALTER DATABASE [Monteflix] SET QUERY_STORE = OFF
GO
USE [Monteflix]
GO
/****** Object:  Table [dbo].[Movies]    Script Date: 3/30/2022 2:39:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Movies](
	[Movie_ID] [int] IDENTITY(1,1) NOT NULL,
	[Movie_Title] [varchar](50) NOT NULL,
	[Movie_Release] [int] NOT NULL,
	[Movie_Genre] [varchar](50) NOT NULL,
	[Movie_Trailer] [varchar](100) NULL,
	[Movie_Image] [varchar](100) NULL,
	[Movie_Watch] [varchar](100) NULL,
	[Movie_Rating] [varchar](100) NULL,
 CONSTRAINT [PK_Movies] PRIMARY KEY CLUSTERED 
(
	[Movie_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 3/30/2022 2:39:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[User_ID] [int] IDENTITY(1,1) NOT NULL,
	[User_Name] [varchar](50) NOT NULL,
	[User_Email] [varchar](50) NOT NULL,
	[User_Password] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[User_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users_Movies]    Script Date: 3/30/2022 2:39:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users_Movies](
	[Users_Movies_ID] [int] IDENTITY(1,1) NOT NULL,
	[FUser_ID] [int] NOT NULL,
	[FMovie_ID] [int] NOT NULL,
	[Users_Movies_Review] [varchar](50) NULL,
 CONSTRAINT [PK_Users_Movies] PRIMARY KEY CLUSTERED 
(
	[Users_Movies_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Users] ON 
GO
INSERT [dbo].[Users] ([User_ID], [User_Name], [User_Email], [User_Password]) VALUES (1, N'Admin', N'monteflix.admin@gmail.com', N'admin123')
GO
INSERT [dbo].[Users] ([User_ID], [User_Name], [User_Email], [User_Password]) VALUES (2, N'Test', N'test@gmail.com', N'test123')
GO
INSERT [dbo].[Users] ([User_ID], [User_Name], [User_Email], [User_Password]) VALUES (3, N'John', N'john@gmail.com', N'john123')
GO
SET IDENTITY_INSERT [dbo].[Users] OFF
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [NonClusteredIndex-20220327-220243]    Script Date: 3/30/2022 2:39:14 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [NonClusteredIndex-20220327-220243] ON [dbo].[Users]
(
	[User_Name] ASC,
	[User_Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Users_Movies]  WITH CHECK ADD  CONSTRAINT [FK_Users_Movies_Movies] FOREIGN KEY([FMovie_ID])
REFERENCES [dbo].[Movies] ([Movie_ID])
GO
ALTER TABLE [dbo].[Users_Movies] CHECK CONSTRAINT [FK_Users_Movies_Movies]
GO
ALTER TABLE [dbo].[Users_Movies]  WITH CHECK ADD  CONSTRAINT [FK_Users_Movies_Users] FOREIGN KEY([FUser_ID])
REFERENCES [dbo].[Users] ([User_ID])
GO
ALTER TABLE [dbo].[Users_Movies] CHECK CONSTRAINT [FK_Users_Movies_Users]
GO
USE [master]
GO
ALTER DATABASE [Monteflix] SET  READ_WRITE 
GO
